### PR TITLE
#162036474 Implement signup feature

### PR DESCRIPTION
**Pull request by PromasterGuru**
#### What does this PR do?
Have user registration.

#### Description of Task to be completed?

1. Create a model with fields representing user information.
2. Create test cases for the registration feature.
3. Creates the registration feature.

#### How should this be manually tested?

1. Clone the project to your local machine: `git clone https://github.com/ThaDeveloper/picbuddy.git`
2. cd into picbuddy folder: `cd picbuddy`
3. Create a virtual environment: `virtualenv venv`
4. Activate the virtual environment: `source venv/bin/activate`
5. Install project dependencies: `pip install -r requirements.txt`
5. cd into the project app: `cd picbuddy_api`
6. Make migrations: `python3 manage.py makemigrations`
7. Migrate the project models: `python3 manage.py migrate`
8. Run the server: `python3 manage.py runserver`
9. Test the project on browser or postman via the URL: `127.0.0.1:8000/users/` 

#### Any background context you want to provide?
This feature was implemented using Django version 2.1.3

#### What are the relevant pivotal tracker stories?
[162036474](https://www.pivotaltracker.com/story/show/162036474)

#### Screenshots (if appropriate)
screenshot 2018-11-22 at 17 24 12

### CODE REVIEW

**Comment by ThaDeveloper** [comment]
great implementing TDD, all tests passes. consider ignoring the .vscode folder and deleting .DS_Store as they are unnecessary.

**Comment by codeplus254** [comment]
@PromasterGuru I have run it locally. Everything checks out. Maybe you could add the HTTP methods available on that URL.

**Comment by rkemmy** [comment]
The tests were exhaustive. Good idea to include doc strings. I suggest using postgres instead of sqlite in future.

**Comment by kamyaD** [comment]
Good job on this project Paul, excelent  passing tests.

**Pull request merged**
